In [13]:
import pandas as pd

In [14]:
df=pd.read_csv("hungarian.data")

In [15]:
df

              1254 0 40 1 1 0 0
0       -9 2 140 0 289 -9 -9 -9
1          0 -9 -9 0 12 16 84 0
2           0 0 0 0 150 18 -9 7
3     172 86 200 110 140 86 0 0
4        0 -9 26 20 -9 -9 -9 -9
...                         ...
2934     0 -9 13 12 -9 -9 -9 -9
2935     -9 -9 -9 -9 -9 -9 -9 8
2936      5 84 0 -9 -9 -9 -9 -9
2937         -9 -9 -9 1 1 1 1 1
2938           1 1 -9. -9. name

[2939 rows x 1 columns]

In [16]:
df.head()

           1254 0 40 1 1 0 0
0    -9 2 140 0 289 -9 -9 -9
1       0 -9 -9 0 12 16 84 0
2        0 0 0 0 150 18 -9 7
3  172 86 200 110 140 86 0 0
4     0 -9 26 20 -9 -9 -9 -9

In [17]:
df .describe()

       1254 0 40 1 1 0 0
count               2939
unique              1847
top     1 1 -9. -9. name
freq                 231

In [18]:
df.tail()

           1254 0 40 1 1 0 0
2934  0 -9 13 12 -9 -9 -9 -9
2935  -9 -9 -9 -9 -9 -9 -9 8
2936   5 84 0 -9 -9 -9 -9 -9
2937      -9 -9 -9 1 1 1 1 1
2938        1 1 -9. -9. name